package com.example.filltracking2.ui.theme

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object ThemeManager {
    var isDarkTheme by mutableStateOf(false)
    var currentLanguage by mutableStateOf("English")
    
    // Translation Map
    private val translations = mapOf(
        "English" to mapOf(
            "login_title" to "Welcome Back",
            "login_subtitle" to "Sign in to continue",
            "email" to "Email",
            "password" to "Password",
            "login_button" to "Login",
            "login_error" to "Invalid email or password",
            "home" to "Home",
            "dashboard" to "Home",
            "history" to "History",
            "settings" to "Settings",
            "preferences" to "Preferences",
            "language" to "Language",
            "theme" to "Theme",
            "notifications" to "Notifications",
            "account" to "Account",
            "change_password" to "Change Password",
            "contact_support" to "Contact Support",
            "rate_app" to "Rate the App",
            "about" to "About",
            "version" to "Version",
            "sign_out" to "Sign Out",
            "light" to "Light",
            "dark" to "Dark",
            "normal" to "Normal",
            "urgent" to "Urgent",
            "identification" to "Identification",
            "current_password" to "Current Password",
            "new_password" to "New Password",
            "confirm_password" to "Confirm New Password",
            "update" to "Update Password",
            "success" to "Success!",
            "error_match" to "Passwords don't match",
            "error_wrong" to "Wrong current password",
            "thank_you" to "Thank you for your rating!",
            "new_file" to "New File Record",
            "original_serial" to "Original Serial (Gov)",
            "internal_serial" to "Internal Serial",
            "recipient_name" to "Recipient Name",
            "subject" to "Subject",
            "tracking_dates" to "Tracking Dates",
            "received_gov" to "Received (Gov)",
            "delivered_sector" to "Delivered Sector",
            "registered_app" to "Registered in App",
            "destination_sectors" to "Destination Sectors",
            "attachments" to "Attachments",
            "camera" to "Camera",
            "gallery" to "Gallery",
            "notes" to "Director's Notes",
            "register_button" to "Register Document",
            "doc_details" to "Document Details",
            "internal_serial_label" to "Internal Serial",
            "original_serial_label" to "Original Serial",
            "recipient" to "Recipient",
            "tracking_timeline" to "Tracking Timeline",
            "received_gov_label" to "Received (Gov)",
            "registered_label" to "Registered in App",
            "delivered_label" to "Delivered to Sector",
            "doc_not_found" to "Document not found"
        ),
        "Français" to mapOf(
            "login_title" to "Bon retour",
            "login_subtitle" to "Connectez-vous pour continuer",
            "email" to "E-mail",
            "password" to "Mot de passe",
            "login_button" to "Connexion",
            "login_error" to "E-mail ou mot de passe invalide",
            "home" to "Accueil",
            "dashboard" to "Accueil",
            "history" to "Historique",
            "settings" to "Paramètres",
            "preferences" to "Préférences",
            "language" to "Langue",
            "theme" to "Thème",
            "notifications" to "Notifications",
            "account" to "Compte",
            "change_password" to "Changer le mot de passe",
            "contact_support" to "Contacter le support",
            "rate_app" to "Évaluer l'application",
            "about" to "À propos",
            "version" to "Version",
            "sign_out" to "Déconnexion",
            "light" to "Clair",
            "dark" to "Sombre",
            "normal" to "Normal",
            "urgent" to "Urgent",
            "identification" to "Identification",
            "current_password" to "Mot de passe actuel",
            "new_password" to "Nouveau mot de passe",
            "confirm_password" to "Confirmer le mot de passe",
            "update" to "Mettre à jour",
            "success" to "Succès!",
            "error_match" to "Les mots de passe ne correspondent pas",
            "error_wrong" to "Mot de passe actuel incorrect",
            "thank_you" to "Merci pour votre note!",
            "new_file" to "Nouvel enregistrement",
            "original_serial" to "N° de série original (Gouv)",
            "internal_serial" to "N° de série interne",
            "recipient_name" to "Nom du destinataire",
            "subject" to "Sujet",
            "tracking_dates" to "Dates de suivi",
            "received_gov" to "Reçu (Gouv)",
            "delivered_sector" to "Secteur livré",
            "registered_app" to "Enregistré dans l'app",
            "destination_sectors" to "Secteurs de destination",
            "attachments" to "Pièces jointes",
            "camera" to "Appareil photo",
            "gallery" to "Galerie",
            "notes" to "Notes du directeur",
            "register_button" to "Enregistrer le document",
            "doc_details" to "Détails du document",
            "internal_serial_label" to "Série interne",
            "original_serial_label" to "Série originale",
            "recipient" to "Destinataire",
            "tracking_timeline" to "Chronologie du suivi",
            "received_gov_label" to "Reçu (Gouv)",
            "registered_label" to "Enregistré dans l'app",
            "delivered_label" to "Livré au secteur",
            "doc_not_found" to "Document non trouvé"
        ),
        "العربية" to mapOf(
            "login_title" to "مرحباً بعودتك",
            "login_subtitle" to "قم بتسجيل الدخول للمتابعة",
            "email" to "البريد الإلكتروني",
            "password" to "كلمة المرور",
            "login_button" to "تسجيل الدخول",
            "login_error" to "البريد الإلكتروني أو كلمة المرور غير صالحة",
            "home" to "الرئيسية",
            "dashboard" to "الرئيسية",
            "history" to "السجل",
            "settings" to "الإعدادات",
            "preferences" to "التفضيلات",
            "language" to "اللغة",
            "theme" to "المظهر",
            "notifications" to "الإشعارات",
            "account" to "الحساب",
            "change_password" to "تغيير كلمة المرور",
            "contact_support" to "الاتصال بالدعم",
            "rate_app" to "تقييم التطبيق",
            "about" to "حول",
            "version" to "الإصدار",
            "sign_out" to "تسجيل الخروج",
            "light" to "فاتح",
            "dark" to "داكن",
            "normal" to "عادي",
            "urgent" to "عاجل",
            "identification" to "التعريف",
            "current_password" to "كلمة المرور الحالية",
            "new_password" to "كلمة المرور الجديدة",
            "confirm_password" to "تأكيد كلمة المرور",
            "update" to "تحديث",
            "success" to "تم بنجاح!",
            "error_match" to "كلمات المرور غير متطابقة",
            "error_wrong" to "كلمة المرور الحالية خاطئة",
            "thank_you" to "شكراً لتقييمك!",
            "new_file" to "سجل ملف جديد",
            "original_serial" to "الرقم التسلسلي الأصلي (حكومي)",
            "internal_serial" to "الرقم التسلسلي الداخلي",
            "recipient_name" to "اسم المستلم",
            "subject" to "الموضوع",
            "tracking_dates" to "تاريخ التتبع",
            "received_gov" to "استلام (حكومي)",
            "delivered_sector" to "قطاع التسليم",
            "registered_app" to "مسجل في التطبيق",
            "destination_sectors" to "القطاعات المستهدفة",
            "attachments" to "المرفقات",
            "camera" to "الكاميرا",
            "gallery" to "المعرض",
            "notes" to "ملاحظات المدير",
            "register_button" to "تسجيل الوثيقة",
            "doc_details" to "تفاصيل الوثيقة",
            "internal_serial_label" to "سلسلة داخلية",
            "original_serial_label" to "سلسلة أصلية",
            "recipient" to "المستلم",
            "tracking_timeline" to "الجدول الزمني للتتبع",
            "received_gov_label" to "استلام (حكومي)",
            "registered_label" to "مسجل في التطبيق",
            "delivered_label" to "سلمت للقطاع",
            "doc_not_found" to "الوثيقة غير موجودة"
        ),
        "Deutsch" to mapOf(
            "login_title" to "Willkommen zurück",
            "login_subtitle" to "Anmelden, um fortzufahren",
            "email" to "E-Mail",
            "password" to "Passwort",
            "login_button" to "Anmelden",
            "login_error" to "Ungültige E-Mail oder Passwort",
            "home" to "Startseite",
            "dashboard" to "Startseite",
            "history" to "Verlauf",
            "settings" to "Einstellungen",
            "preferences" to "Präferenzen",
            "language" to "Sprache",
            "theme" to "Design",
            "notifications" to "Benachrichtigungen",
            "account" to "Konto",
            "change_password" to "Passwort ändern",
            "contact_support" to "Support kontaktieren",
            "rate_app" to "App bewerten",
            "about" to "Über",
            "version" to "Version",
            "sign_out" to "Abmelden",
            "light" to "Hell",
            "dark" to "Dunkel",
            "normal" to "Normal",
            "urgent" to "Dringend",
            "identification" to "Identifikation",
            "current_password" to "Aktuelles Passwort",
            "new_password" to "Neues Passwort",
            "confirm_password" to "Neues Passwort bestätigen",
            "update" to "Passwort aktualisieren",
            "success" to "Erfolg!",
            "error_match" to "Passwörter stimmen nicht überein",
            "error_wrong" to "Falsches aktuelles Passwort",
            "thank_you" to "Vielen Dank für Ihre Bewertung!",
            "new_file" to "Neuer Datensatz",
            "original_serial" to "Original-Seriennummer (Gov)",
            "internal_serial" to "Interne Seriennummer",
            "recipient_name" to "Empfängername",
            "subject" to "Betreff",
            "tracking_dates" to "Tracking-Daten",
            "received_gov" to "Empfangen (Gov)",
            "delivered_sector" to "Gelieferter Sektor",
            "registered_app" to "In App registriert",
            "destination_sectors" to "Zielsektoren",
            "attachments" to "Anhänge",
            "camera" to "Kamera",
            "gallery" to "Galerie",
            "notes" to "Notizen des Direktors",
            "register_button" to "Dokument registrieren",
            "doc_details" to "Dokumentdetails",
            "internal_serial_label" to "Interne Seriennummer",
            "original_serial_label" to "Original-Seriennummer",
            "recipient" to "Empfänger",
            "tracking_timeline" to "Tracking-Zeitplan",
            "received_gov_label" to "Empfangen (Gov)",
            "registered_label" to "In App registriert",
            "delivered_label" to "An Sektor geliefert",
            "doc_not_found" to "Dokument nicht gefunden"
        ),
        "Español" to mapOf(
            "login_title" to "Bienvenido de nuevo",
            "login_subtitle" to "Inicie sesión para continuar",
            "email" to "Correo electrónico",
            "password" to "Contraseña",
            "login_button" to "Iniciar sesión",
            "login_error" to "Correo electrónico o contraseña no válidos",
            "home" to "Inicio",
            "dashboard" to "Inicio",
            "history" to "Historial",
            "settings" to "Ajustes",
            "preferences" to "Preferencias",
            "language" to "Idioma",
            "theme" to "Tema",
            "notifications" to "Notificaciones",
            "account" to "Cuenta",
            "change_password" to "Cambiar contraseña",
            "contact_support" to "Contactar con soporte",
            "rate_app" to "Calificar la aplicación",
            "about" to "Acerca de",
            "version" to "Versión",
            "sign_out" to "Cerrar sesión",
            "light" to "Claro",
            "dark" to "Oscuro",
            "normal" to "Normal",
            "urgent" to "Urgente",
            "identification" to "Identificación",
            "current_password" to "Contraseña actual",
            "new_password" to "Nueva contraseña",
            "confirm_password" to "Confirmar nueva contraseña",
            "update" to "Actualizar contraseña",
            "success" to "¡Éxito!",
            "error_match" to "Las contraseñas no coinciden",
            "error_wrong" to "Contraseña actual incorrecta",
            "thank_you" to "¡Gracias por su calificación!",
            "new_file" to "Nuevo registro",
            "original_serial" to "Nº de serie original (Gov)",
            "internal_serial" to "Nº de serie interno",
            "recipient_name" to "Nombre del destinatario",
            "subject" to "Asunto",
            "tracking_dates" to "Fechas de seguimiento",
            "received_gov" to "Recibido (Gov)",
            "delivered_sector" to "Sector entregado",
            "registered_app" to "Registrado en la aplicación",
            "destination_sectors" to "Sectores de destino",
            "attachments" to "Adjuntos",
            "camera" to "Cámara",
            "gallery" to "Galería",
            "notes" to "Notas del director",
            "register_button" to "Registrar documento",
            "doc_details" to "Detalles del documento",
            "internal_serial_label" to "Serie interne",
            "original_serial_label" to "Serie original",
            "recipient" to "Destinatario",
            "tracking_timeline" to "Cronología de seguimiento",
            "received_gov_label" to "Recibido (Gov)",
            "registered_label" to "Registrado en la aplicación",
            "delivered_label" to "Entregado al sector",
            "doc_not_found" to "Documento no encontrado"
        )
    )

    fun getString(key: String): String {
        return translations[currentLanguage]?.get(key) ?: key
    }
}